# Generated by Django 2.1.5 on 2019-01-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='blog',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
